---
name: Docker Images
on:
  workflow_dispatch:

jobs:
  docker-update:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    env:
      GH_REPO: jeanmarie-tts/docscan
    strategy:
      matrix:
        image:
          - name: postgrest/postgrest
            tag: latest
          - name: swaggerapi/swagger-ui
            tag: latest
          - name: clamav/clamav
            tag: latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull Docker Image
        run: docker pull ${{ matrix.image.name }}:${{ matrix.image.tag }}

      - name: Scan Image
        run: docker run aquasec/trivy:latest image --timeout 5m --scanners vuln --exit-code 1 --severity CRITICAL,HIGH, MEDIUM ${{ matrix.image.name }}:${{ matrix.image.tag }}

      - name: Tag Image
        run: docker tag ${{ matrix.image.name }}:${{ matrix.image.tag }} ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.name }}:${{ matrix.image.tag }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Image
        run: docker push ghcr.io/${{ env.GH_REPO }}/${{ matrix.image.name }}:${{ matrix.image.tag }}

  docker-fetch:
    runs-on: ubuntu-latest
    needs: docker-update
    env:
      GH_REPO: jeanmarie-tts/docscan

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Pull PostGREST Docker Image from fhcr
        run: docker pull ghcr.io/${{ env.GH_REPO }}/postgrest/postgrest:latest

