---
name: get image version
on:
  workflow_call:


jobs:
  get-image-versions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch refresh token artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          # name: ${{ matrix.image.tname }}
          name: postgrest

      - name: Update env var
        run: |
          echo "TF_VAR_postgrest=$(cat postgrest.txt)" >> "$GITHUB_ENV"

      - name: Show env var
        run: |
          env