---
name: Terraform apply (single env)

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      TF_VAR_postgrest:
        required: true
        type: string
  

jobs:
  apply:
    name: apply ( ${{ inputs.environment }} )
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: terraform vars
        run: |
          echo "${{ inputs.TF_VAR_postgrest }}"
