---
name: get image version
on:
  push:
    branches:
      - main


jobs:
  get-image-versions:
    runs-on: ubuntu-latest
    outputs:
      postgrest: ${{ steps.read-postgres.outputs.TF_VAR_postgrest }}


    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Fetch refresh token artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          name: postgrest
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: download-image.yml

      - name: read postgrest version
        id: read-postgres
        run: |
          echo "TF_VAR_postgrest=$(cat postgrest.txt)"
          echo "TF_VAR_postgrest=$(cat postgrest.txt)" >> "$GITHUB_OUTPUT"

  deploy_infra:
    name: Deploy infrastructure (dev)
    needs: get-image-versions
    uses: ./.github/workflows/terraform-apply-env.yml
    with:
      environment: "dev"
      TF_VAR_postgrest: ${{ needs.get-image-versions.outputs.postgrest }}